spring:
  kafka:
    bootstrap-servers: dory-01.srvs.cloudkafka.com:9094,dory-02.srvs.cloudkafka.com:9094,dory-03.srvs.cloudkafka.com:9094
    consumer:
      group-id: ${CLOUDKARAFKA_USERNAME}-consumers
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-512
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    test-connection: false
    username: ${SERVICE_MAIL_USERNAME}
    password: ${SERVICE_MAIL_PASSWORD}
    properties:
      mail:
        debug: ${SERVICE_MAIL_IS_DEBUG:false}
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
jnotification:
  queue:
    email-topic: oowxuqiu-email-notification