server:
  port: 0
  servlet:
    context-path: /api
spring:
  application:
    name: jnotification-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${cloudamqp.host}
    port: ${cloudamqp.port}
    password: ${cloudamqp.password}
    username: ${cloudamqp.username}
    virtual-host: ${cloudamqp.virtual-host}
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    test-connection: false
    username: ${SERVICE_MAIL_EMAIL}
    password: ${SERVICE_MAIL_PASSWORD}
    properties:
      mail:
        debug: ${SERVICE_MAIL_IS_DEBUG:false}
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: ${DISCOVERY_HOST}
cloudamqp:
  host: ${CLOUDAMQP_HOST}
  port: ${CLOUDAMQP_PORT}
  password: ${CLOUDAMQP_PASSWORD}
  username: ${CLOUDAMQP_USERNAME}
  virtual-host: ${CLOUDAMQP_VIRTUAL_HOST}
  queues:
    send-template-mail: send-template-mail-queue
jnotification:
  service:
    name: ${spring.application.name}
    email: ${SERVICE_MAIL_EMAIL}